services:
  php:
    build:
      context: .
      dockerfile: ./dockerfiles/php.Dockerfile
    image: php_image
    container_name: php_container
    volumes:
      - ./:/app
    working_dir: /app
    tty: true

  nodejs:
    build:
      context: .
      dockerfile: ./dockerfiles/node.Dockerfile
    image: nodejs_image
    container_name: nodejs_container
    volumes:
      - ./:/app
    stdin_open: true
    tty: true